apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-1
spec:
  replicas: 12
  selector:
    matchLabels:
      app: php-1
  template:
    metadata:
      labels:
        app: php-1
    spec:
      containers:
      - name: php-1
        image: php-scale
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: nginx
        image: php-scale-nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-1
spec:
  selector:
    app: php-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
