apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-2
  template:
    metadata:
      labels:
        app: php-2
    spec:
      containers:
      - name: php-2
        image: php-scale
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "2G"
            cpu: "2"
          limits:
            memory: "2G"
            cpu: "2"
      - name: nginx
        image: php-scale-nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-2
spec:
  selector:
    app: php-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
